version: "3.8"
services:
  pzwg:
    image: linuxserver/wireguard
    container_name: pzwg
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Atlantic/Reykjavik
    volumes:
      - /docker/appdata/config/wg-zomboid:/config
      - /lib/modules:/lib/modules
    ports:
      #- 51820:51820/udp Does a client need this port forwarded?
      - 16261:16261/udp
      - 16262:16262/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - pzwgnet
  zomboid:
    image: gameservermanagers/gameserver:pz
    container_name: pz
    restart: unless-stopped
    volumes:
      - /zomboidserver:/data
    network_mode: service:pzwg

networks:
  pzwgnet:
    driver: bridge