version: "3.8"
services:
  cs2wg:
    image: linuxserver/wireguard
    container_name: cs2wg
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Atlantic/Reykjavik
    volumes:
      - /docker/appdata/config/wg-cs2:/config
      - /lib/modules:/lib/modules
    ports:
      #- 51820:51820/udp Does a client need this port forwarded?
      - 27015:27015/udp
      - 27016:27016/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - cs2wgnet
  cs2:
    image: gameservermanagers/gameserver:cs2
    container_name: cs2server
    restart: unless-stopped
    volumes:
      - /cs2server:/data
    network_mode: service:cs2wg

networks:
  cs2wgnet:
    driver: bridge